service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  profile: epam
  region: eu-west-1

  environment:
    REGION: ${self:provider.region}
    S3_IMPORTS_BACKET: robot-shop-imports
    SQS_URL:
      Ref: ImportedProductsQueue 

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.S3_IMPORTS_BACKET}/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt: [ImportedProductsQueue, Arn]

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true  

functions:
  importProductsFile:
    handler: src/handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  
  importFileParser:
    handler: src/handler.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.S3_IMPORTS_BACKET}
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

resources:
  Resources:
    ImportedProductsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: imported-products

  Outputs:
    ImportedProductsQueue:
      Description: The imported products ARN
      Value: !GetAtt ImportedProductsQueue.Arn
      Export:
        Name: imported-products-queue
